### ISSUE TITLE
Use Java Rx 2

### ISSUE THREAD

**Issue by mathroule** [aritraroy/RxMagneto#11]

**Comment by mathroule** [comment]
See PR https://github.com/aritraroy/RxMagneto/pull/12

**Comment by mradzinski** [comment]
Any news? Pretty much everyone migrated to RxJava 2 already.

**Comment by aritraroy** [comment]
Yes, this library will surely be updated with RxJava 2. But I was unable to find time to do the full migration. Will review PR #12 soon. :-)

**Comment by aritraroy** [comment]
RxJava 2 PR has been merged. Will soon release RxMagneto 2.0 after pushing some more updates to it.
