### ISSUE TITLE
Lambda Expression

### ISSUE THREAD

**Issue by filol** [aritraroy/RxMagneto#2]
Hi,
I wanted to test your library (which looks awesome!) But I have a problem understanding your code. I do not use lambda expressions and I can not "translate" this, especially the "s->" and "trowable->". Can you help me ?

```
Observable<String> changelogObservable = rxMagneto.grabPlayStoreRecentChangelog(packageName);
        changelogObservable.subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe(s -> {
                    if (progressDialog != null && progressDialog.isShowing()) {
                        progressDialog.dismiss();
                    }
                    showResult(mFeatureModelList.get(FeaturesConfig.FEATURE_RECENT_CHANGELOG).getTitle(), s);
                }, throwable -> {
                    if (progressDialog != null && progressDialog.isShowing()) {
                        progressDialog.dismiss();
                    }
                    showResult(getResources().getString(R.string.label_error), throwable.getMessage());
                });
```

**Comment by aritraroy** [comment]
"s" denotes the String returned as the changelog value and "throwable" denoted the Exception that may occur anytime.

I have used lambdas to shorten the code, you can obviously look at the RxJava docs for the enlarged version of it.

**Comment by filol** [comment]
Yes, but what I wanted to know is that they are the names of functions that do not appear since you use lambda expressions?
