### ISSUE TITLE
Crash if google services are blocked

### ISSUE THREAD

**Issue by filol** [aritraroy/RxMagneto#4]
I had a user who had blocked google services using the LuckyPatcher application and when he tries to access the changelog application crash. You may be able to add to your library a check if google services are allowed.

Thanks for your library which is really useful ;)

Here is my error stack if it can help you

`**Exception java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.**
rx.internal.schedulers.ScheduledAction.run (ScheduledAction.java:59)
java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:422)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201 (ScheduledThreadPoolExecutor.java:152)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:265)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
java.lang.Thread.run (Thread.java:841)
arrow_drop_down

**Caused by java.lang.ExceptionInInitializerError:**
org.jsoup.nodes.Document$OutputSettings.<init> (Document.java:372)
org.jsoup.nodes.Document.<init> (Document.java:19)
org.jsoup.parser.TreeBuilder.initialiseParse (TreeBuilder.java:32)
org.jsoup.parser.TreeBuilder.parse (TreeBuilder.java:42)
org.jsoup.parser.HtmlTreeBuilder.parse (HtmlTreeBuilder.java:56)
org.jsoup.parser.Parser.parseInput (Parser.java:32)
org.jsoup.helper.DataUtil.parseByteData (DataUtil.java:135)
org.jsoup.helper.HttpConnection$Response.parse (HttpConnection.java:747)
org.jsoup.helper.HttpConnection.get (HttpConnection.java:250)
com.aritraroy.rxmagneto.RxMagnetoInternal$5.call (RxMagnetoInternal.java:197)
com.aritraroy.rxmagneto.RxMagnetoInternal$5.call (RxMagnetoInternal.java:188)
rx.internal.operators.OnSubscribeCreate.call (OnSubscribeCreate.java:72)
rx.internal.operators.OnSubscribeCreate.call (OnSubscribeCreate.java:32)
rx.Observable.unsafeSubscribe (Observable.java:10346)
rx.internal.operators.OperatorMerge$MergeSubscriber.onNext (OperatorMerge.java:248)
rx.internal.operators.OperatorMerge$MergeSubscriber.onNext (OperatorMerge.java:148)
rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext (OnSubscribeMap.java:77)
rx.internal.operators.OnSubscribeCreate$LatestEmitter.drain (OnSubscribeCreate.java:492)
rx.internal.operators.OnSubscribeCreate$LatestEmitter.onNext (OnSubscribeCreate.java:425)
com.aritraroy.rxmagneto.RxMagnetoInternal$1.call (RxMagnetoInternal.java:55)
com.aritraroy.rxmagneto.RxMagnetoInternal$1.call (RxMagnetoInternal.java:42)
rx.internal.operators.OnSubscribeCreate.call (OnSubscribeCreate.java:72)
rx.internal.operators.OnSubscribeCreate.call (OnSubscribeCreate.java:32)
rx.Observable.unsafeSubscribe (Observable.java:10346)
rx.internal.operators.OnSubscribeMap.call (OnSubscribeMap.java:48)
rx.internal.operators.OnSubscribeMap.call (OnSubscribeMap.java:33)
rx.internal.operators.OnSubscribeLift.call (OnSubscribeLift.java:48)
rx.internal.operators.OnSubscribeLift.call (OnSubscribeLift.java:30)
rx.Observable.unsafeSubscribe (Observable.java:10346)
rx.internal.operators.OnSubscribeMap.call (OnSubscribeMap.java:48)
rx.internal.operators.OnSubscribeMap.call (OnSubscribeMap.java:33)
rx.internal.operators.OnSubscribeLift.call (OnSubscribeLift.java:48)
rx.internal.operators.OnSubscribeLift.call (OnSubscribeLift.java:30)
rx.Observable.unsafeSubscribe (Observable.java:10346)
rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call (OperatorSubscribeOn.java:100)
rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call (CachedThreadScheduler.java:230)
rx.internal.schedulers.ScheduledAction.run (ScheduledAction.java:55)
java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:422)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201 (ScheduledThreadPoolExecutor.java:152)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:265)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
java.lang.Thread.run (Thread.java:841)
arrow_drop_down

**Caused by java.lang.IllegalStateException: Could not read resource entities-xhtml.properties. Make sure you copy resources for org.a.b.i**
org.jsoup.nodes.Entities.load (Entities.java:301)
org.jsoup.nodes.Entities.access$000 (Entities.java:25)
org.jsoup.nodes.Entities$EscapeMode.<init> (Entities.java:53)
org.jsoup.nodes.Entities$EscapeMode.<clinit> (Entities.java:34)
org.jsoup.nodes.Document$OutputSettings.<init> (Document.java:372)
org.jsoup.nodes.Document.<init> (Document.java:19)
org.jsoup.parser.TreeBuilder.initialiseParse (TreeBuilder.java:32)
org.jsoup.parser.TreeBuilder.parse (TreeBuilder.java:42)
org.jsoup.parser.HtmlTreeBuilder.parse (HtmlTreeBuilder.java:56)
org.jsoup.parser.Parser.parseInput (Parser.java:32)
org.jsoup.helper.DataUtil.parseByteData (DataUtil.java:135)
org.jsoup.helper.HttpConnection$Response.parse (HttpConnection.java:747)
org.jsoup.helper.HttpConnection.get (HttpConnection.java:250)
com.aritraroy.rxmagneto.RxMagnetoInternal$5.call (RxMagnetoInternal.java:197)
com.aritraroy.rxmagneto.RxMagnetoInternal$5.call (RxMagnetoInternal.java:188)
rx.internal.operators.OnSubscribeCreate.call (OnSubscribeCreate.java:72)
rx.internal.operators.OnSubscribeCreate.call (OnSubscribeCreate.java:32)
rx.Observable.unsafeSubscribe (Observable.java:10346)
rx.internal.operators.OperatorMerge$MergeSubscriber.onNext (OperatorMerge.java:248)
rx.internal.operators.OperatorMerge$MergeSubscriber.onNext (OperatorMerge.java:148)
rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext (OnSubscribeMap.java:77)
rx.internal.operators.OnSubscribeCreate$LatestEmitter.drain (OnSubscribeCreate.java:492)
rx.internal.operators.OnSubscribeCreate$LatestEmitter.onNext (OnSubscribeCreate.java:425)
com.aritraroy.rxmagneto.RxMagnetoInternal$1.call (RxMagnetoInternal.java:55)
com.aritraroy.rxmagneto.RxMagnetoInternal$1.call (RxMagnetoInternal.java:42)
rx.internal.operators.OnSubscribeCreate.call (OnSubscribeCreate.java:72)
rx.internal.operators.OnSubscribeCreate.call (OnSubscribeCreate.java:32)
rx.Observable.unsafeSubscribe (Observable.java:10346)
rx.internal.operators.OnSubscribeMap.call (OnSubscribeMap.java:48)
rx.internal.operators.OnSubscribeMap.call (OnSubscribeMap.java:33)
rx.internal.operators.OnSubscribeLift.call (OnSubscribeLift.java:48)
rx.internal.operators.OnSubscribeLift.call (OnSubscribeLift.java:30)
rx.Observable.unsafeSubscribe (Observable.java:10346)
rx.internal.operators.OnSubscribeMap.call (OnSubscribeMap.java:48)
rx.internal.operators.OnSubscribeMap.call (OnSubscribeMap.java:33)
rx.internal.operators.OnSubscribeLift.call (OnSubscribeLift.java:48)
rx.internal.operators.OnSubscribeLift.call (OnSubscribeLift.java:30)
rx.Observable.unsafeSubscribe (Observable.java:10346)
rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call (OperatorSubscribeOn.java:100)
rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call (CachedThreadScheduler.java:230)
rx.internal.schedulers.ScheduledAction.run (ScheduledAction.java:55)
java.util.concurrent.Executors$RunnableAdapter.call (Executors.java:422)
java.util.concurrent.FutureTask.run (FutureTask.java:237)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201 (ScheduledThreadPoolExecutor.java:152)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run (ScheduledThreadPoolExecutor.java:265)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:587)
java.lang.Thread.run (Thread.java:841)`

**Comment by aritraroy** [comment]
Thanks for the report but the library doesn't depend on Google Play Services. How can you say that the crash is because of Google Play Services?

**Comment by filol** [comment]
I thought it came from google play services because I had to try my app on a device without access to google play service and crash while its my developer device worked perfectly. But it turns out that after looking a little more the problem occurs when the application is compiled into release (but running in debug). So I'm not sure that the problem come from your library ultimately.

**Comment by aritraroy** [comment]
Thanks for letting me know. This is not an issue because of the library. Hence, I will close this issue. :-)
